# -*- coding: utf-8 -*-
"""Bauanleitung je Konzept — was zum Umsetzen fehlt, steht hier.

Geschlüsselt über die erste Bildkennung, weil Namen doppelt vorkommen
(„Emaille" ist ein Blatt *und* eine Auslage, „Fallblatt" ebenso).

Vier Felder je Konzept:
  spulen    Welche Fläche die Spulfläche ist — die eine mit `data-spulen`.
  zustaende Woran man sieht, was läuft, was gelaufen ist, was gedrückt wird.
  bewegung  Was sich bewegt. Hausregel: sparsam. Bewegt wird, was den Stand
            zeigt; kein Leerlauf-Animieren.
  bib       Wo Sammlung und Suche sitzen. Pflicht in jedem Layout.

Bei den gebauten (K01–K26) ist das eine **Beschreibung**: so ist es gebaut,
abgelesen aus `player.html`. Bei den gezeichneten Blättern (K27–K47) ist es
aus dem Blatt selbst übernommen — die sind bedienbar. Bei K48–K76 ist es ein
**Vorschlag**: diese Blätter sind Standbilder ohne Skript, dort ist nichts
abzulesen. Was dort steht, ist zu prüfen, bevor gebaut wird.
"""

# ── K01–K26 · gebaut. Abgelesen, nicht vorgeschlagen. ────────────────────
GEBAUT = {
 'app_geraet_quer': ('Die Griffzone am Tonarm — gezogen wird am Arm, nicht an der Platte.',
   'Die Platte hält an, wenn pausiert wird; der Tonarm steht auf der Rille der Position.',
   'Die Platte dreht sich, solange Ton läuft. Der Tonarm ist gerechnet, nicht geraten.',
   'Knopf unten in der Skalenreihe, Blende über das Gerät.'),
 'app_werkstisch_quer': ('Die Griffzone am Tonarm.',
   'Wie Gerät; zusätzlich ist der laufende Titel in der Textliste rechts markiert.',
   'Platte dreht bei Ton. Sonst nichts.',
   'Dauerhaft sichtbar rechts, mit Suchzeile darüber — eine von zwei Ausnahmen.'),
 'app_vollbild_quer': ('Die Platte selbst — an den Rillen gezogen.',
   'Gespielte Ringe leuchten, der laufende Ring ist der äußerste helle.',
   'Keine. Der Stand ist der leuchtende Ring, nicht eine Drehung.',
   'Knopf oben rechts, Blende über die Sternkarte.'),
 'app_deck_quer': ('Die Bandleiste unter der Kassette.',
   'Tasten haben Druckpunkt und bleiben gedrückt; der laufende Titel steht im Regal hell.',
   'Keine. Die Wickel stehen still — bewusst, sonst wäre es Zierrat.',
   'Das Regal rechts steht offen, mit Suche — die zweite Ausnahme.'),
 'app_handgeraet_quer': ('Die Bandleiste, hier so breit wie ein Daumen.',
   'Wie Deck.', 'Keine.',
   'Die Auswurftaste öffnet das Regal als Blende.'),
 'app_aufgeschlagen_quer': ('Der Faden — eine Haarlinie, sonst steht nichts da.',
   'Nur die Haarlinie zeigt den Stand. Kein zweiter Hinweis.',
   'Keine. Der Tonarm folgt der Position, gerechnet.',
   'Ein Knopf oben, Blende über die Seite.'),
 'app_register_quer': ('Der Faden.',
   'Zusätzlich die Warteschlange rechts in Haarlinien, laufender Titel hervorgehoben.',
   'Keine.', 'Ein Knopf oben, Blende über die Seite.'),
 'app_bedienteil_quer': ('Das Metallrad — gedreht, nicht gezogen.',
   'Die laufende Hülle im Fach trägt den orangen Rand und „läuft"; die anderen stehen im Schatten.',
   'Keine. Das Rad dreht sich nur unter dem Finger.',
   'Auswurftaste rechts in der Tastenreihe, Blende über das Gerät.'),
 'app_konsole_quer': ('Das Metallrad, hier größer.',
   'Wie Bedienteil.', 'Keine.', 'Wie Bedienteil.'),
 'app_pult_quer': ('Das Band unter der Platte.',
   'Der laufende Titel ist in der Titelliste links markiert.',
   'Platte dreht bei Ton; der Tonarm ist gerechnet.',
   'Ein Schalter unten links, Blende über das Pult.'),
 'app_turm_quer': ('Die Laufleiste an der Frontplatte.',
   'Zeiger stehen auf dem Pegel; der laufende Titel ist in der Vierer-Wahl hell.',
   'Die Zeiger folgen dem Pegel. Sonst nichts.',
   'Knopf an der Bedienplatte, Blende über beide Geräte.'),
 'app_vollverstaerker_quer': ('Die Laufleiste.',
   'Wie Turm, auf einer Frontplatte statt zweier.', 'Zeiger.', 'Wie Turm.'),
 'app_papier': ('Der Rand im rechten Bildschirmrand — ein Strich je Titel.',
   'Der laufende Titel ist der helle Strich; Namen erscheinen nur beim Ziehen.',
   'Keine. Die Achse zeigt, sie bewegt sich nicht von selbst.',
   'Zwei Knöpfe im Kopf: links Sammlung, rechts Suche — Browsen weckt die Tastatur nicht.'),
 'app_wueste': ('Dieselbe Achse, waagerecht als Skala unter dem Bild.',
   'Wie Papier.',
   'Keine. Auf der Skala ist ein Tippen eindeutig ein Sprung — keine 8-px-Schwelle.',
   'Wie Papier.'),
 'app_kissen': ('Die Balkenreihe.',
   'Gelaufene Balken sind gefüllt, der laufende trägt den Akzent.',
   'Keine.', 'Wie Papier.'),
 'app_karte': ('Der Ausschlag unter der Zeitüberschrift.',
   'Kopflinie auf der Position; darunter die Warteschlange mit markiertem Titel.',
   'Keine.', 'Wie Papier.'),
 'app_kiesel': ('Die Schiene in der Zeile des laufenden Titels.',
   'Der Spieler *ist* die laufende Zeile; der nächste Titel wird angetippt.',
   'Keine.', 'Wie Papier.'),
 'app_tag': ('Gar nicht — es gibt genau einen Knopf.',
   'Der Ring um den Knopf ist der Stand. Play/Pause am Knopf selbst.',
   'Keine.',
   'Keine. Bewusst: keine Sammlung, keine Suche, kein zweiter Knopf.'),
 'app_abzug_hoch': ('Die Bahn unter Titel und Interpret.',
   'Laufender Titel in „Danach" markiert; Taste gefüllt.',
   'Keine.', 'Zwei Knöpfe im Kopf, Blende über die Seite.'),
 'app_entwicklung_hoch': ('Die Bahn.',
   'Wie Der echte Abzug.',
   '<b>Der Abzug entwickelt sich</b>: die Milchschicht geht zurück und das Bild '
   'gewinnt Farbe und Kontrast — beides über <code>--p</code>, den Stand im Titel. '
   'Das ist die einzige Bewegung und zugleich die zweite Standanzeige.',
   'Wie Der echte Abzug.'),
 'app_milchglas_hoch': ('Die Bahn unter der Liste.',
   'Die laufende Zeile ist die hellere Scheibe.',
   'Keine. Das unscharfe Cover hinter der Seite wechselt mit dem Album, es bewegt sich nicht.',
   'Wie Der echte Abzug.'),
 'app_programmheft_hoch': ('Die Bahn.',
   'Der laufende Titel liegt unter dem Textmarker und trägt einen Bleistifthaken.',
   'Keine.', 'Wie Der echte Abzug.'),
 'app_spur_hoch': ('Die Bahn.',
   'Jede Zeile trägt ihren eigenen Stand als Linie: vor der laufenden voll, danach leer.',
   'Nur die Linie der laufenden Zeile wächst. Kein zweiter bewegter Teil.',
   'Wie Der echte Abzug.'),
 'app_emaille_hoch': ('Die Bahn auf der Bedienplatte.',
   'Laufender Titel auf der Listenplatte markiert; Haupttaste gefüllt.',
   'Keine.', 'Wie Der echte Abzug.'),
 'app_gespritzt_hoch': ('Die Bahn.',
   'Wie Emaille; die Haupttaste ist hier ein Ring statt einer Fläche.',
   'Keine.', 'Wie Der echte Abzug.'),
 'app_kalender_hoch': ('Die Bahn auf dem obersten Blatt.',
   'Das oberste Blatt ist der laufende Titel; die kommenden liegen gestaffelt darunter.',
   'Keine — auch kein Abreißen. Das hatte die Vorlage nicht, und es wäre eine Erfindung.',
   'Wie Der echte Abzug.'),
}

# ── K27–K47 · gezeichnet. Aus dem Blatt übernommen, dort bedienbar. ──────
BLATT = {
 'blatt15v1': ('Die Feinskala; das Band <i>wählt</i> das Album.',
   'Das Skalenband zeigt die Nachbaralben; die Marke steht auf dem laufenden.',
   'Keine. Im Ruhezustand ist es ein lesbares, beschriftetes Skalenband.',
   'Das Band selbst ist die Sammlung — Abstimmen ist Suchen.'),
 'blatt16v1': ('Die laufende Zeile selbst.',
   'Die Warteschlange ist die Tafel; der laufende Titel ist die oberste Zeile.',
   '<b>Beim Titelwechsel klappen die Zeichen um</b> — die einzige Bewegung, und die '
   'ist der ganze Entwurf. Ohne sie ist es keine Fallblattanzeige.',
   'Knopf an der Tafel, Blende darüber.'),
 'blatt16v2': ('Wie Abfahrtstafel.', 'Wie Abfahrtstafel.',
   'Wie Abfahrtstafel, in Emaille und Messing statt Schwarz.', 'Wie Abfahrtstafel.'),
 'blatt17v1': ('Der Filmstreifen unter dem Fadenkreuz.',
   'Das laufende Dia liegt unter der Lupe, die übrigen daneben auf dem Milchglas.',
   'Keine. Die Lupe steht, der Streifen läuft unter ihr durch.',
   'Der Leuchttisch selbst ist die Sammlung — die Dias liegen offen.'),
 'blatt17v2': ('Wie Kontaktbogen.', 'Wie Kontaktbogen.', 'Keine.', 'Wie Kontaktbogen.'),
 'blatt18v1': ('Das Zählwerk hochdrehen.',
   'Der Zählerstand <i>ist</i> die Position in der Schlange; vier Tasten mit Druckpunkt.',
   'Die Rollen drehen sich beim Spulen — nicht von selbst.',
   'Knopf am Gehäuse, Blende darüber.'),
 'blatt18v2': ('Wie Stenorette.', 'Wie Stenorette.', 'Wie Stenorette.', 'Wie Stenorette.'),
 'blatt19v1': ('Die Scheibe drehen — eine Umdrehung je Album.',
   'Die rote Ablesemarke steht still, die Scheibe dreht sich unter ihr.',
   'Die Scheibe folgt der Position. Sonst nichts.',
   'Knopf an der Achse, Blende darüber.'),
 'blatt19v2': ('Wie Zinkguss.', 'Wie Zinkguss.', 'Wie Zinkguss, als Papierdrehscheibe.',
   'Wie Zinkguss.'),
 'blatt20v1': ('Die gespannte Kordel; Knoten sitzen an den Titelgrenzen.',
   'Der Pegel ist gestickt; der laufende Titel steht am Knoten.',
   'Keine.', 'Knopf auf der Terrazzoplatte, Blende darüber.'),
 'blatt21v1': ('In jede Schiene greifen — auch in eine fremde, dann springt es dorthin.',
   'Der laufende Titel glüht und trägt die Kapsel; gespielte sind matt warm aufgefüllt.',
   'Das Glühen folgt der Position. Kein Flackern.',
   'Knopf über der Bank, Blende darüber.'),
 'blatt21v2': ('Über Titelgrenzen hinweg — <code>seekGlobal</code>.',
   'Eine Schiene für die ganze Warteschlange, feine Marken an den Titelgrenzen.',
   'Wie Glutbank.', 'Wie Glutbank.'),
 'blatt22v1': ('Am Lichtsaum unter der Pille.',
   'Der Schein wächst mit der Zeit — das ist die Anzeige.',
   'Der Schein. Sonst nichts.',
   'Das Suchfeld steht in der Mitte und ist der Zugang — wie in der Vorlage.'),
 'blatt22v2': ('Am Lichtsaum unter der Tafel.',
   'Wie Lupe.', 'Wie Lupe.',
   'Die Sammlung liegt offen daneben, die Suchzeile direkt darüber.'),
 'blatt23v1': ('An der dunklen Bahn unter dem Spieler.',
   'Jeder Titel eine Plakette, <b>genau eine ist hell</b> — das ist die ganze Zustandslehre.',
   'Keine.', 'Eine Plakette in der Reihe führt hinein.'),
 'blatt23v2': ('Wie Plaketten.', 'Wie Plaketten.', 'Keine.',
   'Hinter einer Plakette, nicht offen.'),
 'blatt24v1': ('Am Streifen in der Zeile des laufenden Titels.',
   'Kalt ist, was gespielt wurde; warm ist, was läuft. Die laufende Karte ist aufgeklappt.',
   'Keine.', 'Der Stapel rechts ist die Sammlung.'),
 'blatt24v2': ('Am Streifen der vorderen Karte.',
   'Je weiter ein Titel von der Gegenwart weg ist, desto tiefer steht er im Raum.',
   'Keine.', 'Wie Stapel.'),
 'blatt25v1': ('Im Ausschlag, 66 px hoch.',
   'Gelaufene Balken dunkel, der laufende orange. Orange sitzt an genau zwei Stellen.',
   'Die Platte dreht sich nur, solange Ton läuft — die zweite Anzeige.',
   'Knopf oben rechts, Blende darüber.'),
 'blatt25v2': ('Über Titelgrenzen hinweg — <code>seekGlobal</code>.',
   'Das Band trägt die ganze Warteschlange, feine Striche an den Grenzen.',
   'Wie Eisblau.', 'Wie Eisblau.'),
 'blatt25v3': ('Im Ausschlag, 60 px hoch — Daumenbreite.',
   'Wie Eisblau.', 'Wie Eisblau.',
   'Knopf oben rechts; die Blende ist hier einspaltig.'),
}

# ── K48–K76 · Vorschlag. Diese Blätter sind Standbilder ohne Skript. ─────
#    Hausregel: bewegt wird, was den Stand zeigt. Kein Leerlauf-Animieren.
#    Jede Zeile hier ist zu prüfen, bevor gebaut wird.
VORSCHLAG = {
 # ── Paket ───────────────────────────────────────────────────────────────
 'foto18_Akai-747': ('Der Zeitstrahl unter dem Titel, über die volle Breite.',
   'Tasten mit Lampe: PLAY grün, PAUSE gelb, sonst dunkel. Der laufende Titel steht in der '
   'Spulenliste links hell.',
   'Der VU-Zeiger folgt dem Pegel — das ist bei einem Bandgerät die Anzeige und kein Zierrat. '
   '<b>Die Spulen drehen sich nicht</b>: zwei laufende Wickel wären reine Dekoration und der '
   'einzige Dauerläufer im ganzen Satz.',
   'Die Taste LIBRARY am Ende der Tastenreihe, Blende über die Frontplatte.'),
 'foto33a_Glass-Musiknote-Ohne': ('Die Bahn unter dem Titel.',
   'Der laufende Titel in der Liste hell, die übrigen gedämpft; Haupttaste gefüllt.',
   'Keine. Das Blatt lebt von der Ruhe der Milchglaskarte.',
   'Der Glaskreis oben rechts, Blende über die Karte.'),
 'foto33b_Glass-Musiknote-Dezent': ('Die Bahn.',
   'Wie Glass ohne Kreise.',
   'Keine. <b>Offen zu entscheiden:</b> ob die Farbwolken beim Albumwechsel die Cover-Farben '
   'annehmen. Das wäre eine Bewegung je Album, nicht je Sekunde — vertretbar, aber neu.',
   'Wie Glass ohne Kreise.'),
 'foto22_EA-Archive': ('Die orange Bahn unter „NOW PLAYING".',
   'PLAY ist das orange gefüllte Feld der Leiste; der laufende Titel im Spec-Raster fett.',
   'Keine. Ein Archivblatt bewegt sich nicht.',
   'ARCHIVE als fünftes Feld der Tastenleiste, Blende über das Blatt.'),
 'foto52_platzhalter': ('', '', '', ''),
 'foto24_Mix-Tape-Klar': ('Die rote Bahn unter der Titelliste.',
   'Der laufende Titel trägt den roten Punkt, die übrigen einen grauen.',
   'Keine. <b>Zu entscheiden:</b> ob die Wickel der durchsichtigen Kassette mitlaufen — hier '
   'wäre es ausnahmsweise Anzeige und nicht Zierrat, weil man durch die Schale sieht, wie viel '
   'Band noch übrig ist.',
   'Der runde Knopf mit Bibliothekszeichen neben Weiter.'),
 'foto25_Audio-Tape-C90': ('Die Bahn unter der Kassette.',
   'Balkentasten sind gedrückt oder nicht; laufender Titel in der Liste hervorgehoben.',
   'Keine.', 'Der orange Block LIBRARY am Ende der Tastenleiste.'),
 'foto26_True-Sound': ('Die Bahn.',
   'Die Titelliste ist farbcodiert; der laufende Titel trägt den vollen Ton, die übrigen einen blassen.',
   'Keine.', 'Die Pille LIBRARY in der Tastenreihe.'),
 'foto27_Stereo-60': ('Die Bahn im gerahmten Feld.',
   'Rahmen-Tasten mit sichtbarem Druckzustand; laufender Titel im Rahmen markiert.',
   'Keine.', 'Der umrandete Knopf LIBRARY.'),
 'foto31_Vinyl-Rote-Tasten': ('Der Slider — die Sprechblase darüber ist die Zeit und wandert mit.',
   'Die drei roten Rundtasten haben einen Druckzustand; laufender Titel in der Liste fett.',
   'Die Sprechblase folgt dem Griff. <b>Die Platte dreht sich nicht</b> — sie ist hier Bild, '
   'nicht Laufwerk; es gibt keinen Tonarm, der eine Drehung erklären würde.',
   'Die eigene Kachel mit Bibliothekszeichen oben rechts.'),
 'foto34_Retro-Party': ('Die Bahn unter dem Plakat.',
   'Rahmen-Tasten mit Druckzustand; der laufende Titel im Programm hervorgehoben.',
   'Keine. <b>Zu entscheiden:</b> ob die Strahlen im Hintergrund sich drehen. Ich rate ab — '
   'ein Dauerläufer hinter Text macht ihn schwer lesbar.',
   'Der Rahmen-Knopf CRATE.'),
 'foto35_Music-Sounds-Better': ('Die rote Bahn unter der Titelliste.',
   'Die gefüllte rote Kreis-Taste ist Play/Pause; der laufende Titel steht gesperrt und dunkel, '
   'die übrigen grau.',
   'Keine. Das Blatt ist der Pilot gerade deshalb: es hat nichts, worüber man streiten müsste.',
   'Der runde Knopf mit Bibliothekszeichen in der Reihe.'),
 'foto36_Song-Poster-Schwarz': ('Die Bahn unter dem Spiraltext.',
   'Kreis-Tasten mit Druckzustand; im Rahmen sitzt der Tonarm auf der Position.',
   '<b>Zu entscheiden:</b> Der Spiraltext <i>ist</i> die Rille — die Platte zu drehen wäre hier '
   'ausnahmsweise sinnvoll, weil der Tonarm sonst über stehendem Text schwebt. Mein Vorschlag: '
   'der Tonarm wandert, die Platte steht. Eine Drehung würde den Text unlesbar machen.',
   'Der runde Knopf mit Bibliothekszeichen neben Repeat.'),
 'foto37_Song-Poster-Weiss': ('Die Bahn.',
   'Beschriftete Tasten (SHUFFLE, PREV, PLAY, NEXT, REPEAT) mit Druckzustand.',
   'Wie Song-Poster schwarz.',
   'Der Knopf SAMMLUNG rechts in der Tastenreihe.'),
 'foto38_World-Music-Day': ('Die Bahn im Programmfeld.',
   'Der laufende Titel im Line-up hervorgehoben; Tasten mit Druckzustand.',
   'Keine. Blitze und Stern sind Plakat, nicht Anzeige.',
   'Der Knopf LINE-UP am Ende der Tastenleiste.'),

 # ── Eigene Entwürfe ─────────────────────────────────────────────────────
 'foto39_Kippschalter': ('<b>Offen — hier fehlt am meisten.</b> Der Entwurf ist reine Typografie; '
   'eine Bahn gibt es nicht. Vorschlag: die Grundlinie unter dem Titel wird zur Spulfläche.',
   'Die beiden Kippschalter sind oben oder unten — das ist Wiedergabe/Pause und zugleich das Bild.',
   'Der Kippschalter kippt beim Umschalten. Das ist die eine Bewegung, und sie ist die Bedienung '
   'selbst, nicht ihre Verzierung.',
   'Vorschlag: ein dritter Schalter oder ein Wort in der Kopfzeile — im Blatt nicht vorgesehen.'),
 'foto43_Sonnenglas': ('Die Bahn auf der Glaskarte.',
   'Die Karte trägt Titel und Zeit; der laufende Titel in der Liste hell.',
   'Keine. Der Himmel ist Grund und darf nicht wandern.',
   'Die Glaspille über der Karte.'),
 'foto43b_Klarglas': ('Die Bahn auf der Karte.', 'Wie Sonnenglas.',
   'Keine. <b>Zu entscheiden:</b> ob der Spiegelstreifen beim Ziehen mitwandert — das wäre eine '
   'schöne Rückmeldung und kostet fast nichts.',
   'Die Glaspille über der Karte.'),
 'foto43f_Rauchglas': ('Die Bahn auf der Karte.', 'Wie Sonnenglas.', 'Wie Klarglas.',
   'Die Glaspille über der Karte.'),
 'foto44_Geraetezeile': ('Die Haarlinie.',
   'Das Dreieck zeigt Wiedergabe; bei Pause steht ein Doppelstrich. Mehr gibt die Zeile nicht her.',
   'Keine. Das ist das kargste Display im Satz und soll es bleiben.',
   'Vorschlag: ein Wort links in der Zeile — im Blatt nicht vorgesehen, muss dazu.'),
 'foto46_Malerblatt': ('Der gezogene Strich unter dem Stillleben.',
   'Der Strich ist der Fortschritt; er ist gemalt und endet dort, wo die Position steht.',
   'Keine. <b>Zu entscheiden:</b> ob der Strich beim Wachsen wie gemalt ausläuft. Das wäre die '
   'einzige Stelle, an der eine Bewegung dem Entwurf etwas hinzufügt.',
   'Vorschlag: ein Wort am Blattrand — im Blatt nicht vorgesehen.'),
 'foto48_Siebdruck': ('Die Bahn unter den Versalien.',
   'Zwei Farben, kein Grau: gelaufener Teil gelb, Rest oranger Grund.',
   'Keine. Ein Siebdruck bewegt sich nicht.',
   'Vorschlag: ein Wort in der Fußzeile — im Blatt nicht vorgesehen.'),
 'foto50_Fallblatt': ('Die Bahn unter den Fallblättern.',
   'Die beiden Fallblätter zeigen Titelnummer und Laufzeit.',
   '<b>Beim Titelwechsel klappen die Blätter um</b> — wie beim gezeichneten Blatt 16. Ohne das '
   'ist es ein Wecker ohne Klappzahlen.',
   'Der Drehknopf öffnet die Sammlung.'),
 'foto51_Tastenfeld_iphone': ('Die Bahn im Glasfeld oben.',
   'Die Quadrate unten sind die Bedienung; das gedrückte ist gefüllt.',
   'Keine.', 'Die grüne Taste ist die Sammlung — im Blatt bereits vorgesehen.'),
 'foto53_Fokusmodul': ('Die Bahn im Modul.',
   'Das Modul zeigt genau einen Zustand hell.',
   'Keine.', 'Vorschlag: eine Kachel im Modul — im Blatt zu prüfen.'),
 'foto56_Punktring': ('Der Ring — gezogen wird auf dem Kreis.',
   'Der Punkt auf dem Ring ist die Position; gelaufener Bogen kräftiger.',
   'Der Punkt wandert auf dem Ring. Sonst nichts.',
   'Vorschlag: die Mitte des Rings öffnet die Sammlung.'),
 'foto58_Zeigerfront': ('Der Zeitstrahl unter der Tastenreihe.',
   'Die waagerechte Tastenreihe zeigt den gedrückten Knopf; der Ring rechts ist die Lautstärke.',
   'Die beiden VU-Zeiger folgen dem Pegel — dafür sind sie da.',
   'Vorschlag: eine Taste in der Reihe — im Blatt zu prüfen.'),
 'foto60_Klimaxfront': ('Die Haarlinie unter Titel und Lautstärke.',
   'Weiss für das, was gilt, gedämpftes Grau für das, was es beschreibt. Kein Akzent, keine Farbe.',
   'Keine. Die Vorlage dimmt im Ruhezustand auf schwarzes Glas — <b>zu entscheiden</b>, ob wir '
   'das übernehmen. Es wäre die einzige Bewegung und ein starkes Bild.',
   'Die Quellenzeile links im Feld: die Sammlung ist eine Quelle wie jede andere.'),
 'foto61_Fernanzeige': ('Die Haarlinie über der unteren Reihe.',
   'Nur zwei Zeichen: Lautstärke als Zahl links, Wiedergabe rechts. Kein dritter Zustand.',
   'Keine. Eine Einblendung, die sich bewegt, ist keine Einblendung mehr.',
   'Die Quellenzeile oben in der Mitte, wo an einem Gerät der Quellenname stünde.'),
 'foto62_Leuchtmarke': ('Die Skala selbst — über Titelgrenzen hinweg, <code>seekGlobal</code>.',
   'Der rote Keil ist die Gegenwart; Rot kommt sonst nirgends vor. Titelgrenzen stehen als '
   'hohe Striche zwischen den feinen.',
   '<b>Der Keil wandert, und die Schärfe wandert mit ihm</b>: der Schleier ist dort '
   'durchsichtig, wo er steht. Das ist Anzeige, nicht Zierrat — neben der Gegenwart liest man '
   'genau ab, am Rand nur ungefähr.',
   'Die Quellenzeile oben links.'),
}
del VORSCHLAG['foto52_platzhalter']

BAU = {}
for q, art in ((GEBAUT, 'gebaut'), (BLATT, 'blatt'), (VORSCHLAG, 'vorschlag')):
    for k, v in q.items():
        BAU[k] = {'art': art, 'spulen': v[0], 'zustaende': v[1],
                  'bewegung': v[2], 'bib': v[3]}
